services:
  db_mysql:
    image: mysql:8.0
    container_name: db_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: clazzbridge
      MYSQL_PASSWORD: clazz123!
    volumes:
      - ./db_mysql/data:/var/lib/mysql

  db_redis:
    image: redis:alpine
    container_name: db_redis
    ports:
      - "6379:6379"
    volumes:
      - ./db_redis/data:/data

  backend_websocket:
    build:
      context: ./BackEnd-WebSocket
      dockerfile: Dockerfile
    container_name: backend_websocket
    ports:
      - "3000:3000"
    volumes:
      - ./BackEnd-WebSocket/src:/usr/src/app
    environment:
      NODE_ENV: production
      REDIS_URL: redis://db_redis:6379
    depends_on:
      - db_redis

  backend_spring:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: backend_spring
    ports:
      - "8080:8080"
    volumes:
      - ./config/application.properties:/home/quitendexit/git/Refactoring-Clazzbridge/BackEnd/src/main/resources/application.properties
    environment:
      SPRING_PROFILE_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://db_mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: clazzbridge
      SPRING_DATASOURCE_PASSWORD: clazz123!
      SPRING_CONFIG_LOCATION: /home/quitendexit/git/Refactoring-Clazzbridge/BackEnd/src/main/resources/application.properties
      SPRING_JWT_SECRET: c2V1bGtpYW5nIHN0cmluZyBmb3IgYmFzZTY0IGVuY29kaW5n
    depends_on:
      - db_mysql

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./FrontEnd/build:/user/share/nginx/html
    environment:
      REACT_APP_API_URL: http://backend_spring:8080/api/
      REACT_APP_SOCKET_SERVER_URI: http://backend_websocket:3000
      REACT_APP_SOCKET_HOST: ws
      REACT_APP_PORT: 3000
    depends_on:
      - backend_spring
      - backend_websocket

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/data:/var/jenkins_home
    environment:
      JENKINS_OPT: --httpPort=8080