apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  type: LoadBalancer  # 외부에서 접근 가능하도록 LoadBalancer 설정
  ports:
    - port: 8080
      targetPort: 8080  # 컨테이너가 사용하는 포트와 매핑
  selector:
    app: back  # Deployment와 매칭되는 레이블
